#!/bin/env python
import sys
import os
from shlex import quote
from pathlib import Path
from subprocess import Popen

file = sys.argv[1]

if file.find('./') == 0:
    file = str(Path(os.getcwd()) / file[2:])

if not os.path.exists(file):
    raise FileExistsError(file)

if len(sys.argv) >= 2:
    args = ' -- ' + ' '.join(sys.argv[2:])
else:
    args = ''

background = ''

with open(file, 'r') as f:
    f = f.read()
    if f.find('\n# BACKGROUND') != -1:
        background = ' --background '

Popen(f'blender {background} --python ' + quote(file) + args, shell=True)
